# -*- coding: utf-8 -*-
"""Copy of Modern Desktop Audio Player

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rgbUyG18NlJ3S2nXOtBzYmUDaDuvN5i0
"""

import tkinter as tk
from tkinter import filedialog, ttk
import pygame.mixer as mixer
import os
import time

# --- Firebase and User/App Context (Required for Canvas Environment) ---
# NOTE: This application does not use Firestore, but these context variables
# are included for compliance with the platform structure.
__app_id = 'audio-player-app'
__firebase_config = '{}'
__initial_auth_token = ''

class AudioPlayerApp:
    """
    A single-file Python Tkinter application for a simple desktop audio player.
    Uses pygame.mixer for robust audio playback.
    """
    def __init__(self, master):
        self.master = master
        master.title("Modern Desktop Audio Player")
        master.geometry("500x300")
        master.configure(bg='#1E1E1E') # Dark background

        # Initialize the audio mixer (non-blocking audio engine)
        try:
            mixer.init()
        except mixer.error as e:
            print(f"Error initializing mixer: {e}. Check your audio drivers.")
            # Create a simple message box (instead of alert)
            self.show_message("Error", f"Failed to initialize audio mixer: {e}", "red")
            return

        # State Variables
        self.current_track = ""
        self.is_paused = False
        self.track_length_seconds = 0
        self.playback_thread = None # Placeholder for future seeking/timing thread

        # --- Configure Styles (Tkinter Themed Widgets - ttk) ---
        style = ttk.Style()
        style.theme_use('clam') # 'clam' theme looks decent on dark background

        # Custom styles for dark theme
        style.configure('TFrame', background='#1E1E1E')
        style.configure('TButton', background='#2D2D2D', foreground='white', font=('Inter', 10, 'bold'), borderwidth=0, relief='flat')
        style.map('TButton', background=[('active', '#404040')], foreground=[('active', 'white')])
        style.configure('TLabel', background='#1E1E1E', foreground='#FFFFFF', font=('Inter', 11))
        style.configure('TScale', background='#1E1E1E')

        # --- Layout Frames ---
        self.main_frame = ttk.Frame(master, padding="20 20 20 20")
        self.main_frame.pack(fill=tk.BOTH, expand=True)

        self.info_frame = ttk.Frame(self.main_frame)
        self.info_frame.pack(pady=10, fill=tk.X)

        self.control_frame = ttk.Frame(self.main_frame)
        self.control_frame.pack(pady=15)

        self.volume_frame = ttk.Frame(self.main_frame)
        self.volume_frame.pack(pady=10, fill=tk.X)

        # --- Track Information Widgets ---
        self.track_title_label = ttk.Label(self.info_frame, text="No track loaded", font=('Inter', 14, 'bold'), foreground='#90CAF9')
        self.track_title_label.pack(pady=5, anchor='w')

        self.status_label = ttk.Label(self.info_frame, text="Status: Stopped", foreground='#AAAAAA')
        self.status_label.pack(pady=2, anchor='w')

        # --- Control Buttons ---

        # Load Button (File Management)
        self.load_button = ttk.Button(self.control_frame, text="Load Track", command=self.load_track)
        self.load_button.grid(row=0, column=0, padx=10)

        # Play/Pause Button
        self.play_pause_button = ttk.Button(self.control_frame, text="▶ Play", command=self.toggle_play_pause, state=tk.DISABLED)
        self.play_pause_button.grid(row=0, column=1, padx=10)

        # Stop Button
        self.stop_button = ttk.Button(self.control_frame, text="■ Stop", command=self.stop_track, state=tk.DISABLED)
        self.stop_button.grid(row=0, column=2, padx=10)

        # --- Volume Control ---
        ttk.Label(self.volume_frame, text="Volume: ").pack(side=tk.LEFT, padx=(0, 10))

        self.volume_slider = ttk.Scale(self.volume_frame, from_=0, to=100, orient=tk.HORIZONTAL, command=self.set_volume, length=200)
        self.volume_slider.set(50) # Default volume 50%
        self.volume_slider.pack(side=tk.LEFT, fill=tk.X, expand=True)
        self.set_volume(50) # Set mixer volume immediately

    def show_message(self, title, message, color='blue'):
        """Displays a message box in the UI instead of using alert()."""
        # Create a transient top-level window for the message
        msg_box = tk.Toplevel(self.master)
        msg_box.title(title)
        msg_box.geometry("300x100")
        msg_box.transient(self.master)
        msg_box.grab_set()

        # Center the message box relative to the main window
        x = self.master.winfo_x() + (self.master.winfo_width() - 300) // 2
        y = self.master.winfo_y() + (self.master.winfo_height() - 100) // 2
        msg_box.geometry(f"+{x}+{y}")

        ttk.Label(msg_box, text=message, foreground=color, font=('Inter', 10), wraplength=280).pack(pady=10, padx=10)
        ttk.Button(msg_box, text="OK", command=msg_box.destroy).pack(pady=5)
        self.master.wait_window(msg_box)

    def load_track(self):
        """Opens a file dialog to select an audio file and loads it."""
        audio_file = filedialog.askopenfilename(
            defaultextension=".mp3",
            filetypes=[
                ("Audio Files", "*.mp3 *.wav *.ogg"),
                ("MP3 Files", "*.mp3"),
                ("WAV Files", "*.wav"),
                ("All Files", "*.*")
            ]
        )

        if audio_file:
            self.stop_track() # Stop any currently playing track
            try:
                # Load the audio file into the mixer channel
                mixer.music.load(audio_file)
                self.current_track = audio_file

                # Update UI elements
                base_name = os.path.basename(audio_file)
                self.track_title_label.config(text=base_name)

                # Enable controls
                self.play_pause_button.config(state=tk.NORMAL)
                self.stop_button.config(state=tk.NORMAL)

                self.status_label.config(text="Status: Ready to Play")
                self.is_paused = False # Reset pause state

                # Simple way to get approximate length (0.01 is a small placeholder value)
                self.track_length_seconds = 0.01

                # Automatically start playing after loading
                self.play_track()

            except mixer.error as e:
                error_msg = f"Failed to load audio file: {audio_file}. Error: {e}"
                print(error_msg)
                self.show_message("File Error", error_msg, "red")
                self.reset_ui()
            except Exception as e:
                print(f"An unexpected error occurred during loading: {e}")
                self.reset_ui()


    def play_track(self):
        """Starts playing the loaded track from the beginning or from pause."""
        if not self.current_track:
            self.show_message("Error", "Please load an audio file first.", "orange")
            return

        # Play the track
        mixer.music.play()
        self.is_paused = False
        self.play_pause_button.config(text="⏸ Pause")
        self.status_label.config(text="Status: Playing")

    def toggle_play_pause(self):
        """Toggles between Play and Pause states."""
        if not self.current_track:
            return

        if self.is_paused:
            mixer.music.unpause()
            self.is_paused = False
            self.play_pause_button.config(text="⏸ Pause")
            self.status_label.config(text="Status: Playing")
        else:
            mixer.music.pause()
            self.is_paused = True
            self.play_pause_button.config(text="▶ Play")
            self.status_label.config(text="Status: Paused")

    def stop_track(self):
        """Stops playback and rewinds the track."""
        mixer.music.stop()
        self.is_paused = False
        self.play_pause_button.config(text="▶ Play", state=tk.NORMAL) # Ready to play from start
        self.status_label.config(text="Status: Stopped")

    def set_volume(self, value):
        """Sets the volume of the mixer based on the slider value."""
        # Tkinter scale passes the value as a string
        volume = float(value) / 100.0
        mixer.music.set_volume(volume)

    def reset_ui(self):
        """Resets the UI elements to the initial state."""
        self.current_track = ""
        self.track_title_label.config(text="No track loaded")
        self.status_label.config(text="Status: Stopped")
        self.play_pause_button.config(state=tk.DISABLED)
        self.stop_button.config(state=tk.DISABLED)

    def on_closing(self):
        """Handles cleanup before closing the application."""
        self.stop_track()
        mixer.quit()
        self.master.destroy()

if __name__ == "__main__":
    # The main Tkinter loop starts here
    root = tk.Tk()
    app = AudioPlayerApp(root)
    # Set the cleanup function
    root.protocol("WM_DELETE_WINDOW", app.on_closing)
    root.mainloop()